#!/usr/bin/env sh
# ATROPOS installer.
#
#   curl -fsSL https://raw.githubusercontent.com/mjmichaelware/ATROPOS/main/install.sh | sh
#
# Downloads a prebuilt jar rather than compiling. The engine is a 967-file
# Kotlin tree whose compile needs more heap than a phone has spare, which is
# the whole reason this exists: the device that most needs to run ATROPOS is
# the one least able to build it.
#
# POSIX sh, not bash. Termux ships several shells and this has to run under
# whichever one is there.
set -eu

REPO="${ATROPOS_REPO:-mjmichaelware/ATROPOS}"
# The rolling build from main by default. Set ATROPOS_VERSION=v2.0.0 for a
# fixed release, which is what a bug report should cite.
VERSION="${ATROPOS_VERSION:-latest}"
PREFIX="${ATROPOS_PREFIX:-$HOME/.atropos}"
BIN_DIR="${ATROPOS_BIN_DIR:-$HOME/.local/bin}"

JAR_URL="https://github.com/$REPO/releases/download/$VERSION/ATROPOS.jar"
SHA_URL="$JAR_URL.sha256"

say()  { printf '%s\n' "$*"; }
fail() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- what the host must already have --------------------------------------
# Checked before anything is downloaded, so a missing dependency costs no
# bandwidth on a metered connection.
command -v java >/dev/null 2>&1 || fail \
  "java not found. ATROPOS needs a JVM (17 or newer).
  Termux:  pkg install openjdk-21
  Debian:  sudo apt install openjdk-21-jre-headless"

JAVA_MAJOR=$(java -version 2>&1 | head -1 | sed -n 's/.*version "\([0-9]*\).*/\1/p')
if [ -n "${JAVA_MAJOR:-}" ] && [ "$JAVA_MAJOR" -lt 17 ] 2>/dev/null; then
  fail "java $JAVA_MAJOR found, 17 or newer required."
fi

if command -v curl >/dev/null 2>&1; then
  DOWNLOAD='curl -fsSL -o'
elif command -v wget >/dev/null 2>&1; then
  DOWNLOAD='wget -qO'
else
  fail "neither curl nor wget found."
fi

# --- fetch ------------------------------------------------------------------
mkdir -p "$PREFIX" "$BIN_DIR"
TMP="$PREFIX/.ATROPOS.jar.part"

say "Downloading ATROPOS ($VERSION) ..."
$DOWNLOAD "$TMP" "$JAR_URL" || fail \
  "download failed from $JAR_URL
  If this is a fresh repository the release may not exist yet -- push to main
  once so the Release JAR workflow can publish it."

# --- verify -----------------------------------------------------------------
# A jar is executable code. Checking it against the hash the build published is
# the difference between installing what was built and installing whatever
# answered the request.
if $DOWNLOAD "$TMP.sha256" "$SHA_URL" 2>/dev/null; then
  EXPECTED=$(tr -d ' \n\r\t' < "$TMP.sha256")
  if command -v sha256sum >/dev/null 2>&1; then
    ACTUAL=$(sha256sum "$TMP" | awk '{print $1}')
  elif command -v shasum >/dev/null 2>&1; then
    ACTUAL=$(shasum -a 256 "$TMP" | awk '{print $1}')
  else
    ACTUAL=""
    say "note: no sha256 tool found; skipping verification."
  fi
  if [ -n "$ACTUAL" ] && [ "$ACTUAL" != "$EXPECTED" ]; then
    rm -f "$TMP" "$TMP.sha256"
    fail "checksum mismatch.
  expected $EXPECTED
  actual   $ACTUAL
  The download was corrupted or tampered with. Nothing was installed."
  fi
  rm -f "$TMP.sha256"
else
  say "note: no published checksum for $VERSION; skipping verification."
fi

mv "$TMP" "$PREFIX/ATROPOS.jar"

# --- launcher ---------------------------------------------------------------
# A script rather than an alias, so it works from any shell and from other
# programs. `exec` so signals and the exit code belong to the JVM: Ctrl-C in
# the CLI must reach ATROPOS, not a wrapper standing in front of it.
cat > "$BIN_DIR/atropos" <<EOF
#!/usr/bin/env sh
# Generated by the ATROPOS installer. Re-run the installer to update.
exec java \${ATROPOS_JAVA_OPTS:-} -jar "$PREFIX/ATROPOS.jar" "\$@"
EOF
chmod +x "$BIN_DIR/atropos"

say ""
say "Installed:"
say "  jar      $PREFIX/ATROPOS.jar"
say "  launcher $BIN_DIR/atropos"

case ":$PATH:" in
  *":$BIN_DIR:"*) say ""; say "Run it:  atropos" ;;
  *)
    say ""
    say "$BIN_DIR is not on your PATH. Add it:"
    say "  echo 'export PATH=\"\$PATH:$BIN_DIR\"' >> ~/.profile && . ~/.profile"
    say ""
    say "Or run it directly:  $BIN_DIR/atropos"
    ;;
esac

say ""
say "ATROPOS reads and writes only inside the directory you launch it from."
say "Start it from the project you want it to work on."
