/* SPDX-License-Identifier: AGPL-3.0-only */
package atropos.core.verification

/** Atomic concern categories used by the architecture compliance gate. */
enum class ArchitectureConcern(val label: String, val markers: List<Regex>) {
    ROUTING(
        "routing",
        listOf(
            Regex("""\bwhen\s*\(\s*tokens"""),
            Regex("""RouterOutcome"""),
            Regex("""fun\s+route\b"""),
            Regex("""\bdef\s+route\b""")
        )
    ),
    RENDERING(
        "rendering",
        listOf(
            Regex("""\bui\.render"""),
            Regex("""atropos\.cli\.ui\."""),
            Regex("""\bappendLine\("""),
            Regex("\u001B\\["),
            Regex("""\bprint\(""")
        )
    ),
    SESSION_STATE(
        "session-state",
        listOf(
            Regex("""SessionTabs"""),
            Regex("""\bvar\s+active[A-Z]"""),
            Regex("""QuotaSessionTracker""")
        )
    ),
    TRANSPORT(
        "transport",
        listOf(
            Regex("""HttpURLConnection"""),
            Regex("""\.openConnection\("""),
            Regex("""ProcessBuilder\("""),
            Regex("""\bsubprocess\.""")
        )
    ),
    NORMALIZATION(
        "normalization",
        listOf(
            Regex("""fun\s+\w*[Nn]ormaliz"""),
            Regex("""fun\s+\w*[Pp]arse\w*Response"""),
            Regex("""JSONObject"""),
            Regex("""\bjson\.(loads|dumps)\(""")
        )
    ),
    VERIFICATION(
        "verification",
        listOf(
            Regex("""VerificationResult"""),
            Regex("""fun\s+verify\b"""),
            Regex("""DeterministicVerifier"""),
            Regex("""\bdef\s+verify\b""")
        )
    ),
    EXECUTION(
        "execution",
        listOf(
            Regex("""\.start\(\)"""),
            Regex("""waitFor\("""),
            Regex("""fun\s+execute\b"""),
            Regex("""\bdef\s+execute\b""")
        )
    ),
    SOURCE_LOADING(
        "source-loading",
        listOf(
            Regex("""Files\.walk"""),
            Regex("""readLines"""),
            Regex("""readText"""),
            Regex("""loadDocuments"""),
            Regex("""\bPath\([^)]*\)\.read_text\(""")
        )
    ),
    ADDRESS_PARSING(
        "address-parsing",
        listOf(
            Regex("""fun\s+parse\b"""),
            Regex("""parseSelector"""),
            Regex("""ParsedDloiAddress"""),
            Regex("""\bdef\s+parse\b""")
        )
    );
}
