/* SPDX-License-Identifier: AGPL-3.0-only */
package atropos.cli.input

object CommandCatalog {
    val catalog: List<CommandEntry> = listOf(
        CommandEntry("/help", "show command help", "System", aliases = listOf("/usage", "/?", "/commands")),
        CommandEntry("/shortcuts", "every keyboard shortcut", "System", aliases = listOf("/keys-help")),
        CommandEntry("/ps", "ask a second provider without joining the queue", "Models"),
        CommandEntry("/pipeline", "what ATROPOS does, stage by stage", "System"),
        CommandEntry("/scavenge", "find public work people asked for help with", "System"),
        CommandEntry("/start", "the first three steps, checked against this install", "System", aliases = listOf("/first-run")),
        CommandEntry("/dashboard", "return to dashboard"),
        CommandEntry("/home", "return to dashboard"),
        CommandEntry("/tabs", "list open tabs"),
        CommandEntry("/tab new", "open a new tab"),
        CommandEntry("/tab rename", "rename a tab"),
        CommandEntry("/tab close", "close a tab"),
        CommandEntry("/tab next", "switch to next tab"),
        CommandEntry("/tab prev", "switch to previous tab"),
        CommandEntry("/status", "session status"),
        CommandEntry("/doctor", "read-only backend, provider, and MCP diagnostics"),
        CommandEntry("/status adapters", "provider adapter matrix"),
        CommandEntry("/status assets", "asset route status"),
        CommandEntry("/status endpoints", "operation registry"),
        CommandEntry("/status failures", "provider failure summary"),
        CommandEntry("/status quota", "quota ledger"),
        CommandEntry("/status route", "provider route decision (add --full for expanded cascade details)"),
        CommandEntry("/providers", "provider inventory"),
        CommandEntry("/mcp", "local MCP servers and health"),
        CommandEntry("/mcp search <query>", "search configured MCP entries without installing or downloading servers"),
        CommandEntry("/mcp call <server> <tool>", "call one allowlisted local MCP tool"),
        CommandEntry("/mcp ingest <path>", "convert a repository file through allowlisted MarkItDown and attest markdown"),
        CommandEntry("/providers --full", "expanded provider inventory with capabilities and requirements"),
        CommandEntry("/providers inventory", "provider inventory grouped by category"),
        CommandEntry("/providers descriptors --full", "expanded provider contracts and environment requirements"),
        CommandEntry("/providers matrix", "read-only provider task routing matrix"),
        CommandEntry("/providers descriptors", "provider contract grid"),
        CommandEntry("/providers validate", "provider descriptor validation"),
        CommandEntry("/providers verify", "offline provider verification (use <id> or all)"),
        CommandEntry("/providers live-test", "explicit free/credit provider live test"),
        CommandEntry("/providers list", "local provider health inventory"),
        CommandEntry("/providers refresh", "refresh local provider discovery"),
        CommandEntry("/providers test", "cheap local provider health test"),
        CommandEntry("/providers prefer", "prefer a healthy provider"),
        CommandEntry("/providers disable", "disable a provider locally"),
        CommandEntry("/providers connect", "connect a provider through local secret storage"),
        CommandEntry("/agent", "agent bridge"),
        CommandEntry("/agent status", "agent bridge status"),
        CommandEntry("/agent run", "durable agent job runner"),
        CommandEntry("/agent run --smoke", "durable agent job runner with local smoke"),
        CommandEntry("/agent enqueue", "durable agent queue enqueue"),
        CommandEntry("/agent enqueue --smoke", "durable agent queue enqueue with local smoke"),
        CommandEntry("/agent queue", "recent durable agent queue entries"),
        CommandEntry("/agent queue show", "durable agent queue entry details"),
        CommandEntry("/agent queue run next", "run one eligible queued agent item"),
        CommandEntry("/agent queue run --max", "run a bounded number of queued agent items"),
        CommandEntry("/agent queue resume", "resume a nonterminal queued agent item"),
        CommandEntry("/agent queue cancel", "cancel a queued or running agent item"),
        CommandEntry("/agent queue recover", "recover stale durable queue leases"),
        CommandEntry("/agent queue doctor", "run isolated durable queue diagnostics"),
        CommandEntry("/agent daemon once", "run one queued agent item through daemon control"),
        CommandEntry("/agent daemon foreground", "run local queue daemon in foreground"),
        CommandEntry("/agent daemon start", "start local queue daemon process"),
        CommandEntry("/agent daemon stop", "request local queue daemon stop"),
        CommandEntry("/agent daemon status", "local queue daemon status"),
        CommandEntry("/agent daemon doctor", "isolated local daemon diagnostics"),
        CommandEntry("/agent jobs", "recent agent jobs"),
        CommandEntry("/agent job", "agent job details (use --raw for full record)"),
        CommandEntry("/agent job --raw", "full raw agent job record"),
        CommandEntry("/agent ask", "agent bridge ask"),
        CommandEntry("/agent patch", "agent bridge patch placeholder"),
        CommandEntry(
            "/agent worker propose",
            "propose a territory-bounded worker patch without applying it",
            "Agent",
            keywords = listOf("worker", "proposal", "territory", "bounded")
        ),
        CommandEntry("/agent apply", "agent bridge safe patch apply"),
        CommandEntry("/agent apply --check", "agent bridge patch validation"),
        CommandEntry("/agent apply --verify", "agent bridge patch apply and verify"),
        CommandEntry("/agent verify", "agent bridge verification"),
        CommandEntry("/agent repair", "agent bridge repair"),
        CommandEntry("/route", "preview routing decision"),
        CommandEntry("/dloi lookup", "exact source lookup by document/section/line address"),
        CommandEntry("/dloi resolve", "resolve a task to an authoritative source section"),
        CommandEntry("/ast lookup", "exact Kotlin symbol lookup"),
        CommandEntry("/use", "switch provider"),
        CommandEntry("/use auto", "automatic routing"),
        CommandEntry("/verbose", "toggle expandable execution and provider-stage output"),
        CommandEntry("/debug", "alias for verbose execution output"),
        CommandEntry("/verify", "verification scope"),
        CommandEntry("/verify narrow", "quick verification"),
        CommandEntry("/verify wide", "wide verification"),
        CommandEntry("/keys", "key status"),
        CommandEntry("/keys setup", "local secret template setup"),
        CommandEntry("/keys status", "key source status"),
        CommandEntry("/keys doctor", "key precedence and provider impact doctor"),

        // SUP.AUTH.*: the governing documents and their attestation state.
        CommandEntry(
            "/auth",
            "attestation state of every governing document",
            "Authority",
            keywords = listOf("agents.md", "swarm.md", "attest", "fingerprint", "drift")
        ),
        CommandEntry("/auth verify", "report each authority document as attested, changed or absent", "Authority"),
        CommandEntry("/auth cascade", "which layer wins each key, and which keys no layer may override", "Authority"),
        CommandEntry(
            "/auth accept",
            "record a document's current contents as authoritative after reviewing the change",
            "Authority",
            example = "/auth accept AGENTS.md"
        ),

        // SUP.STOR.*: storage as a visible, bounded, collectable resource.
        CommandEntry(
            "/storage",
            "usage against the declared ceiling, per class",
            "Observe",
            aliases = listOf("/gc"),
            keywords = listOf("disk", "space", "ceiling", "free", "quota")
        ),
        CommandEntry("/storage policy", "the retention tier and window governing each stored class", "Observe"),
        CommandEntry(
            "/storage gc",
            "report what could be reclaimed; add --apply to actually delete",
            "Observe",
            example = "/storage gc worktrees --apply"
        ),

        // SUP.UX.INTERRUPT-PRIMITIVE: stopping without losing the work.
        CommandEntry(
            "/interrupt",
            "stop the running loop at its next safe boundary",
            "Agent",
            keywords = listOf("stop", "cancel", "ctrl-c", "abort", "halt")
        ),
        CommandEntry("/interrupt soft", "finish the current tool, then stop", "Agent"),
        CommandEntry("/interrupt hard", "stop the current tool now; work in flight is abandoned", "Agent"),
        CommandEntry("/interrupt status", "whether an interrupt is pending or has been taken", "Agent"),
        CommandEntry(
            "/pause",
            "freeze the run, preserving its exact position for /resume",
            "Agent",
            keywords = listOf("freeze", "suspend", "later")
        ),
        CommandEntry(
            "/resume",
            "continue a frozen run from the position it stopped at",
            "Agent",
            keywords = listOf("continue", "unfreeze", "restore")
        ),

        // HOE-B03/HOE-E04: reasoning at the depth this surface asked for.
        CommandEntry(
            "/thinking",
            "how much of the engine's reasoning to show while it works",
            "Observe",
            keywords = listOf("reasoning", "verbose", "detail", "trace", "progress", "watch"),
            example = "/thinking 3"
        ),
        CommandEntry("/thinking 1", "outline only — milestones as they pass", "Observe"),
        CommandEntry("/thinking 2", "reasoning — what the engine did and why", "Observe"),
        CommandEntry("/thinking 3", "full trace — everything, including evidence detail", "Observe"),
        CommandEntry("/thinking replay", "re-show what has happened so far at the current depth", "Observe"),

        // SUP.UX.ANSI-SCHEME-TOKENS: the accents Source Doc 5 asks for.
        CommandEntry(
            "/theme",
            "the colour scheme, and how to change it",
            "Orient",
            keywords = listOf("color", "colour", "ansi", "palette", "scheme", "dark", "accent"),
            example = "/theme atropos-purple"
        ),
        CommandEntry("/theme list", "every available theme", "Orient"),
        CommandEntry("/theme preview", "each theme rendered in its own palette", "Orient"),
        CommandEntry("/theme reset", "return to the default red", "Orient"),

        // SUP.ART.HANDOFF-EXPORT: artifacts leaving through a checked channel.
        CommandEntry(
            "/export",
            "write a handoff, report, evidence summary, swarm status or audit out of the system",
            "Observe",
            keywords = listOf("handoff", "report", "download", "artifact", "share"),
            example = "/export handoff --downloads"
        ),
        CommandEntry("/factory", "factory status"),
        CommandEntry("/factory plan", "bounded app-factory plan"),
        CommandEntry("/factory run", "queue app-factory run"),
        CommandEntry("/factory answer", "persist YES/NO factory clarification answers", "Build", keywords = listOf("factory", "confidence", "clarification", "yes", "no")),
        CommandEntry(
            "/self-host",
            "run the Phase 11 self-build loop (use /self-host status for read-only status)",
            "Self-host",
            aliases = listOf("/agent self-host")
        ),
        CommandEntry(
            "/self-host run",
            "run Phase 11 self-host loop from a natural-language goal",
            "Self-host",
            aliases = listOf("/agent self-host run")
        ),
        CommandEntry(
            "/self-host start",
            "start a durable self-hosting goal",
            "Self-host",
            aliases = listOf("/agent self-host start")
        ),
        CommandEntry(
            "/self-host status",
            "self-hosting goal status",
            "Self-host",
            aliases = listOf("/agent self-host status")
        ),
        CommandEntry(
            "/self-host watch",
            "watch self-hosting goal events",
            "Self-host",
            aliases = listOf("/agent self-host watch")
        ),
        CommandEntry(
            "/self-host resume",
            "resume the next ready DAG node",
            "Self-host",
            aliases = listOf("/agent self-host resume")
        ),
        CommandEntry(
            "/self-host recover",
            "recover restart state and continue self-hosting",
            "Self-host",
            aliases = listOf("/agent self-host recover")
        ),
        CommandEntry(
            "/self-host next",
            "show next autonomous self-host action",
            "Self-host",
            aliases = listOf("/agent self-host next")
        ),
        CommandEntry(
            "/self-host stop",
            "stop a self-hosting goal",
            "Self-host",
            aliases = listOf("/agent self-host stop")
        ),
        CommandEntry(
            "/self-host verify",
            "verify self-hosting goal state",
            "Self-host",
            aliases = listOf("/agent self-host verify")
        ),
        CommandEntry(
            "/self-host promote",
            "promote a verified candidate JAR safely",
            "Self-host",
            aliases = listOf("/agent self-host promote")
        ),
        CommandEntry(
            "/self-host export-evidence",
            "export self-host evidence bundle",
            "Self-host",
            aliases = listOf("/agent self-host export-evidence")
        ),
        CommandEntry(
            "/self-host history",
            "self-hosting goal history",
            "Self-host",
            aliases = listOf("/agent self-host history")
        ),
        CommandEntry(
            "/self-host learned",
            "learned experiences from self-hosting",
            "Self-host",
            aliases = listOf("/agent self-host learned")
        ),
        CommandEntry(
            "/self-host benchmark",
            "self-hosting benchmark summary",
            "Self-host",
            aliases = listOf("/agent self-host benchmark")
        ),
        CommandEntry("/memory", "memory status"),
        CommandEntry("/paid", "paid emergency gate"),
        CommandEntry("/paid status", "paid emergency status"),
        CommandEntry("/pwd", "show shell cwd"),
        CommandEntry("/cd", "change shell cwd"),
        CommandEntry("/ls", "list files through shell bridge"),
        CommandEntry("/git status", "git status through shell bridge"),
        CommandEntry("/git diff", "read-only git diff through the bounded shell bridge"),
        CommandEntry("/shell", "run explicit shell command"),
        CommandEntry("/exit", "close session"),
        CommandEntry("/quit", "close session"),
        CommandEntry("/director", "director advisory mode status"),
        CommandEntry("/director observe", "record a director observation"),
        CommandEntry("/director report", "advisory report of unacknowledged observations"),
        CommandEntry("/director acknowledge", "acknowledge a director observation"),
        CommandEntry("/director dismiss", "dismiss a director observation"),
        CommandEntry("/director scan", "scan working tree diff for drift and violations"),
        CommandEntry("/territory", "territory enforcement status"),
        CommandEntry("/territory assign", "assign territory to an owner"),
        CommandEntry("/territory revoke", "revoke a territory assignment"),
        CommandEntry("/territory violations", "list territory violations"),
        CommandEntry("/territory resolve", "resolve a territory violation"),
        CommandEntry("/hr", "HR Router status"),
        CommandEntry("/hr route", "route a cross-boundary information request"),
        CommandEntry("/hr audit", "HR Router audit log"),
        CommandEntry("/auditor", "auditor status and report"),
        CommandEntry("/auditor run", "run auditor checks"),
        CommandEntry("/custodian", "custodian status and report"),
        CommandEntry("/custodian clean", "run custodian temp file cleanup"),
        CommandEntry("/custodian prune", "prune dead snapshots"),
        CommandEntry("/hierarchy", "agent hierarchy status"),
        CommandEntry("/hierarchy register", "register an agent in the hierarchy"),
        CommandEntry("/hierarchy snapshot", "current hierarchy snapshot"),
        CommandEntry("/hierarchy escalate", "show escalation path for an agent"),
        CommandEntry("/dag status", "DAG compilation and coverage status"),
        CommandEntry("/dag ingest", "ingest a source document into the DAG"),
        CommandEntry("/dag nodes", "list DAG nodes"),
        CommandEntry("/dag runnable", "list runnable DAG nodes"),
        CommandEntry("/dag cycles", "detect dependency cycles in the DAG"),
        CommandEntry("/dag hig", "Hierarchical Implementation Gap report"),
        CommandEntry("/dag snapshot", "current DAG snapshot"),
        CommandEntry("/snapshot", "multimodal snapshot status"),
        CommandEntry("/snapshot capture", "capture a terminal/file/viewport snapshot"),
        CommandEntry("/snapshot compare", "compare two snapshots"),
        CommandEntry("/snapshot list", "list recent snapshots"),
        CommandEntry("/inspect", "inspection service status"),
        CommandEntry("/inspect runtime", "inspect the latest recorded runtime observation", "Observe"),
        CommandEntry("/inspect agent", "inspect the latest durable agent goal", "Agent"),
        CommandEntry("/inspect provider", "inspect the active provider truth", "Models"),
        CommandEntry("/inspect policy", "inspect a governance proposal verdict", "Governance"),
        CommandEntry("/inspect authority", "inspect loaded authority documents and hashes", "Authority"),
        CommandEntry("/inspect recovery", "inspect the latest persisted recovery snapshot", "Observe"),
        CommandEntry("/inspect file", "inspect file for drift against prior snapshot"),
        CommandEntry("/inspect dag", "verify DAG state against expected completions"),
        CommandEntry("/inspect viewport", "verify viewport content contains expected pattern"),
        CommandEntry("/inspect full", "run full multimodal inspection"),
        CommandEntry("/inspect preview-patch", "validate and preview a bounded unified patch", "Observe"),
        CommandEntry("/snapshot report", "inspection report"),
        CommandEntry("/platform", "platform descriptor and environment"),
        CommandEntry("/platform adapters", "list available platform adapters"),
        CommandEntry("/platform health", "platform health status"),
        CommandEntry("/platform env", "platform environment details"),
        CommandEntry("/artifact", "artifact pipeline status"),
        CommandEntry("/artifact plan", "plan an artifact build from prompt"),
        CommandEntry("/artifact build", "metadata-only artifact build; use natural language or /factory run for a project"),
        CommandEntry("/artifact verify", "verify artifact integrity"),
        CommandEntry("/artifact install", "install artifact to target directory"),
        CommandEntry("/artifact commit", "prepare commit candidate from artifacts"),
        CommandEntry("/artifact gate", "run acceptance gate on artifact"),
        CommandEntry("/autonomous", "autonomous orchestrator status"),
        CommandEntry("/autonomous init", "initialize autonomous session"),
        CommandEntry("/autonomous tick", "run one autonomous orchestrator tick"),
        CommandEntry("/autonomous run", "run one eligible autonomous task"),
        CommandEntry("/autonomous run-max", "run up to N autonomous tasks"),
        CommandEntry("/autonomous backlog", "show autonomous task backlog"),
        CommandEntry("/autonomous repairs", "show repair history"),
        CommandEntry("/autonomous failovers", "show provider failover history"),

        CommandEntry("/project", "durable project registry", "Project", aliases = listOf("/projects")),
        CommandEntry("/project list", "list registered projects", "Project"),
        CommandEntry("/project new", "register a project (use <name> [objective])", "Project"),
        CommandEntry("/project show", "project detail by id", "Project"),
        CommandEntry("/project status", "set project status (use <id> <status>)", "Project"),
        CommandEntry("/project objective", "set a project objective (use <id> <text>)", "Project"),
        CommandEntry("/project history", "permanent project event history", "Project"),

        CommandEntry("/tests", "run the built-in test matrix", "Verification"),
        CommandEntry("/tests matrix", "run the built-in test matrix", "Verification"),

        CommandEntry("/security", "secret precedence and redaction status", "Security"),
        CommandEntry("/security redact", "redaction report for supplied text", "Security"),

        CommandEntry("/ci", "ci and edge execution status", "Execution"),
        CommandEntry("/ci local compile", "queue a local compile job", "Execution"),
        CommandEntry("/ci run next", "run the next queued ci job", "Execution"),

        CommandEntry("/ops", "deployment descriptor operations", "Operations"),
        CommandEntry("/ops export", "export deployment descriptor files", "Operations"),
        CommandEntry("/ops verify", "verify exported deployment descriptors", "Operations"),
        CommandEntry("/ops quota-backup", "back up the quota ledger", "Operations"),
        CommandEntry("/ops quota-restore", "restore the quota ledger (use <backup-file>)", "Operations"),

        CommandEntry("/assets", "asset generator status", "Assets"),
        CommandEntry("/assets status", "asset generator status", "Assets"),
        CommandEntry("/assets text", "write a text asset (use <name> <prompt>)", "Assets"),
        CommandEntry("/assets ansi", "write an ansi asset (use <name> <prompt>)", "Assets"),
        CommandEntry("/assets svg", "write an svg asset (use <name> <prompt>)", "Assets"),

        CommandEntry("/diff", "show the current worktree diff with syntax-highlighted hunks", "Repository",
            aliases = listOf("/changes"),
            example = "/diff",
            nlHint = "show me the changes, show diff, what did I change"),
        CommandEntry("/diff --staged", "show staged changes only", "Repository",
            example = "/diff --staged"),
        CommandEntry("/diff <path>", "show diff for a specific file", "Repository",
            example = "/diff src/main/kotlin/Example.kt"),
        CommandEntry("/history", "navigate the session execution timeline", "Session",
            aliases = listOf("/timeline"),
            example = "/history",
            nlHint = "show history, what happened, timeline")
    )
}
