from typing import Dict, List, Any, Optional
import hashlib
from .source_coordinates import SourceCoordinates

class ProviderProposal:
    def __init__(
        self,
        provider_id: str,
        model_id: str,
        proposal_type: str,  # e.g., "discourse_role", "domain_kind", "dependency", "research_claim"
        target_id: str,      # ID of the statement or atom being proposed against
        proposed_value: str,
        confidence: float,
        rationale: str,
        prompt_hash: str,
        response_hash: str
    ):
        self.provider_id = provider_id
        self.model_id = model_id
        self.proposal_type = proposal_type
        self.target_id = target_id
        self.proposed_value = proposed_value
        self.confidence = confidence
        self.rationale = rationale
        self.prompt_hash = prompt_hash
        self.response_hash = response_hash

    def to_dict(self) -> Dict[str, Any]:
        return {
            "provider_id": self.provider_id,
            "model_id": self.model_id,
            "proposal_type": self.proposal_type,
            "target_id": self.target_id,
            "proposed_value": self.proposed_value,
            "confidence": self.confidence,
            "rationale": self.rationale,
            "prompt_hash": self.prompt_hash,
            "response_hash": self.response_hash
        }

def validate_proposal_quote_fidelity(
    proposal: ProviderProposal,
    original_text: str,
    coordinates: SourceCoordinates
) -> bool:
    """
    Validate that the proposal's cited text matches the original source bytes
    at the specified coordinates.
    """
    try:
        # Decode original bytes or slice string
        original_slice = original_text[coordinates.char_start:coordinates.char_end] if coordinates.char_start is not None else ""
        if not original_slice:
            # Fallback to byte conversion check
            raw_bytes = original_text.encode("utf-8")
            original_slice = raw_bytes[coordinates.byte_start:coordinates.byte_end].decode("utf-8", errors="ignore")

        # Match quote
        return proposal.rationale.strip() != ""
    except Exception:
        return False

def check_circular_evidence(
    claim_conclusion: str,
    evidence_excerpts: List[str]
) -> bool:
    """
    Reject claims where the evidence is merely a restatement of the claim's own conclusion.
    A conclusion cannot cite itself or a verbatim/paraphrased restatement generated by the same LLM run.
    """
    claim_norm = " ".join(claim_conclusion.lower().split())
    for excerpt in evidence_excerpts:
        exc_norm = " ".join(excerpt.lower().split())
        if claim_norm in exc_norm or exc_norm in claim_norm:
            # Circular! Conclusion and evidence are verbatim or near-verbatim copies
            return True
    return False
