#!/usr/bin/env bash
set -euo pipefail

echo "=== FAST CLASSES ==="
scripts/atropos-fast-gate.sh classes

echo "=== FULL SMOKE ==="
scripts/atropos-fast-gate.sh smoke

if [[ "${GITHUB_ACTIONS:-false}" == "true" ]]; then
  echo "=== HOSTED ORPHAN GATE ==="
  python3 scripts/find-orphans.py --fail-on-new

  echo "=== PROVIDER CONNECT CONTRACT ==="
  bash scripts/provider-connect-contract-test.sh

  echo "=== HOSTED COMPILE ==="
  ./gradlew --no-daemon compileJava compileTestJava compileKotlin compileTestKotlin

  echo "=== HOSTED FOCUSED BACKEND TESTS ==="
  ./gradlew --no-daemon :test --rerun \
    --tests 'atropos.core.factory.FactoryResumeAndRepairTest' \
    --tests 'atropos.core.factory.FactoryLiveRepairActionTest' \
    --tests 'atropos.core.factory.FactoryProgressGuardTest' \
    --tests 'atropos.core.factory.FactoryRunHandoffTest' \
    --tests 'atropos.core.factory.FactoryObligationLoopTest' \
    --tests 'atropos.core.factory.FactoryAcceptanceFreezeTest' \
    --tests 'atropos.core.factory.FactoryEvidenceWaveExecutorTest' \
    --tests 'atropos.core.factory.FactoryResearchDloiTest' \
    --tests 'atropos.core.factory.AppActionRegistryTest' \
    --tests 'atropos.core.factory.AppAuthPlannerTest' \
    --tests 'atropos.core.factory.AppBackendIntegrationPlannerTest' \
    --tests 'atropos.core.factory.AppDatabaseSecurityPlannerTest' \
    --tests 'atropos.core.factory.AppDeploymentServiceTest' \
    --tests 'atropos.core.factory.AppDurableStoreTest' \
    --tests 'atropos.core.factory.AppFactoryAcceptanceContractTest' \
    --tests 'atropos.core.factory.AppFactoryRouterTest' \
    --tests 'atropos.core.factory.AppGeneratedBehaviorGuardTest' \
    --tests 'atropos.core.factory.AppProjectGeneratorTest' \
    --tests 'atropos.core.factory.BundledSpecGraphTest' \
    --tests 'atropos.core.factory.CanonicalAtomizationTest' \
    --tests 'atropos.core.factory.FactoryLanguageContractTest' \
    --tests 'atropos.core.factory.FactoryLineageTest' \
    --tests 'atropos.core.factory.FactoryRequirementStatementsTest' \
    --tests 'atropos.core.factory.FactoryRunEventRecorderTest' \
    --tests 'atropos.core.factory.FactoryRunRootGuardTest' \
    --tests 'atropos.core.factory.IntentParserTest' \
    --tests 'atropos.core.factory.LanguageAwareScaffoldTest' \
    --tests 'atropos.core.factory.RepositoryVerificationPlannerTest' \
    --tests 'atropos.core.factory.ReservedPackageNameTest' \
    --tests 'atropos.core.provider.ProviderOnboardingTest' \
    --tests 'atropos.core.provider.ProviderActivationServiceTest' \
    --tests 'atropos.core.provider.ProviderCascadeRouterTest' \
    --tests 'atropos.core.provider.ProviderCascadeOrderTest' \
    --tests 'atropos.core.provider.ProviderFailureClassifierTest' \
    --tests 'atropos.core.provider.ActiveSourceBindingResolverTest' \
    --tests 'atropos.core.provider.adapter.AdapterRouteFacadePolicyTest' \
    --tests 'atropos.core.provider.ContextAttestationTest' \
    --tests 'atropos.core.provider.adapter.CredentialSafeHttpTransportTest' \
    --tests 'atropos.core.provider.adapter.AwsSigV4Test' \
    --tests 'atropos.core.provider.adapter.BedrockKernelAdapterTest' \
    --tests 'atropos.core.provider.EligibilityAlgorithmTest' \
    --tests 'atropos.core.provider.FallbackChainRegistryTest' \
    --tests 'atropos.core.provider.FallbackChainTest' \
    --tests 'atropos.core.provider.GitRepositoryMetadataReaderTest' \
    --tests 'atropos.core.provider.LocalRootTest' \
    --tests 'atropos.core.provider.ProviderFailureRedactionTest' \
    --tests 'atropos.core.provider.ProviderFixtureMatrixServiceTest' \
    --tests 'atropos.core.provider.ProviderTruthModelsTest' \
    --tests 'atropos.core.provider.SourceBindingContextPackerTest' \
    --tests 'atropos.core.provider.SourceContextMetricsTest' \
    --tests 'atropos.core.provider.TypedFailureStatesTest' \
    --tests 'atropos.core.provider.ProviderErrorNormalizerTest' \
    --tests 'atropos.core.policy.ProviderActionProposalsTest' \
    --tests 'atropos.core.policy.ActionActorTest' \
    --tests 'atropos.core.policy.BoundedProcessRunnerTest' \
    --tests 'atropos.core.policy.CapabilityEnforcerTest' \
    --tests 'atropos.core.policy.ExecutionPolicyEngineTest' \
    --tests 'atropos.core.policy.LifecycleActionProposalsTest' \
    --tests 'atropos.core.policy.TypedToolExecutorTest' \
    --tests 'atropos.core.provider.QuotaLedgerRouteTruthTest' \
    --tests 'atropos.bridge.BridgeEventsHandlerTest' \
    --tests 'atropos.bridge.BridgeStreamTest' \
    --tests 'atropos.bridge.BridgeEditorHandlerTest' \
    --tests 'atropos.bridge.BridgeEvidenceHandlerTest' \
    --tests 'atropos.bridge.BridgeApprovalHandlerTest' \
    --tests 'atropos.bridge.BridgeMcpHandlerTest' \
    --tests 'atropos.core.integration.McpHostManagerTest' \
    --tests 'atropos.core.integration.AdversarialValidatorTest' \
    --tests 'atropos.core.integration.AndroidShellBridgeTest' \
    --tests 'atropos.core.integration.BridgeEndpointsTest' \
    --tests 'atropos.core.integration.InboundActionProposalBridgeTest' \
    --tests 'atropos.core.integration.InboundToolBridgeTest' \
    --tests 'atropos.core.integration.MarkItDownIngestServiceTest' \
    --tests 'atropos.core.integration.IntegrationRegistryTest' \
    --tests 'atropos.core.sentry.SentryApiClientTest' \
    --tests 'atropos.core.sentry.SentryRepairCoordinatorTest' \
    --tests 'atropos.bridge.BridgeQuotaRouteTest' \
    --tests 'atropos.bridge.BridgeStatusHandlerTest' \
    --tests 'atropos.bridge.projection.SixAnswersProjectionTest' \
    --tests 'atropos.bridge.QuotaProjectionTest' \
    --tests 'atropos.bridge.BridgeComputerUseHandlerTest' \
    --tests 'atropos.bridge.BridgeConversationHandlerTest' \
    --tests 'atropos.bridge.BridgeQueueHandlerTest' \
    --tests 'atropos.bridge.BridgeSelfHostRoutesTest' \
    --tests 'atropos.bridge.BridgeSessionHandlerTest' \
    --tests 'atropos.bridge.GovernanceRoutesTest' \
    --tests 'atropos.bridge.LocalEngineBridgeTest' \
    --tests 'atropos.bridge.conversation.BridgeConversationStoreTest' \
    --tests 'atropos.bridge.conversation.BridgeSessionStoreTest' \
    --tests 'atropos.bridge.conversation.QueuedWorkConversationResponderTest' \
    --tests 'atropos.bridge.http.HttpRequestAuthenticatorTest' \
    --tests 'atropos.bridge.http.HttpRequestParserTest' \
    --tests 'atropos.bridge.http.HttpRouteTableTest' \
    --tests 'atropos.bridge.menu.BridgeMenuCatalogTest' \
    --tests 'atropos.bridge.projection.ActivityProjectionTest' \
    --tests 'atropos.bridge.projection.AuthorityProjectionTest' \
    --tests 'atropos.bridge.projection.CheckpointProjectionTest' \
    --tests 'atropos.bridge.projection.ExportProjectionTest' \
    --tests 'atropos.bridge.projection.ThinkingProjectionTest' \
    --tests 'atropos.bridge.projection.WelcomeProjectionTest' \
    --tests 'atropos.bridge.RecoveryProjectionTest' \
    --tests 'atropos.bridge.BridgeFilesHandlerTest' \
    --tests 'atropos.bridge.AtroposBridgeTest' \
    --tests 'atropos.bridge.menu.HelpRegistryTest' \
    --tests 'atropos.cli.input.CommandRegistryParityTest' \
    --tests 'atropos.cli.BackendDoctorTest' \
    --tests 'atropos.cli.FactoryCommandHandlerTest' \
    --tests 'atropos.cli.CommandRouterHelpTest' \
    --tests 'atropos.cli.CommandRouterIdentityTest' \
    --tests 'atropos.cli.help.HelpGeneratorTest' \
    --tests 'atropos.cli.FirstRunDoctorRendererTest' \
    --tests 'atropos.cli.input.CommandCatalogBackendEntriesTest' \
    --tests 'atropos.core.agent.AgentContextCollectorTest' \
    --tests 'atropos.core.agent.AgentContextExportStoreTest' \
    --tests 'atropos.core.agent.AgentDaemonLogWriterTest' \
    --tests 'atropos.core.agent.AgentDaemonRootResolverTest' \
    --tests 'atropos.core.agent.AgentDaemonStoreTest' \
    --tests 'atropos.core.agent.AgentJobStoreTest' \
    --tests 'atropos.core.agent.AgentPatchAuditorTest' \
    --tests 'atropos.core.agent.AgentPatchBoundedAgencyTest' \
    --tests 'atropos.core.agent.AgentPatchCascadeRunnerTest' \
    --tests 'atropos.core.agent.AgentPatchResponseValidatorTest' \
    --tests 'atropos.core.agent.AgentPatchRunResultFactoryTest' \
    --tests 'atropos.core.agent.AgentQueueRecordCodecCorruptionTest' \
    --tests 'atropos.core.agent.AgentQueueStoreTest' \
    --tests 'atropos.core.agent.AgentRepairAttestationTest' \
    --tests 'atropos.core.agent.AgentRepairBudgetTest' \
    --tests 'atropos.core.agent.AgentRunPromptComposerTest' \
    --tests 'atropos.core.agent.AgentRunRepoStatusTest' \
    --tests 'atropos.core.agent.AgentServiceModelsTest' \
    --tests 'atropos.core.agent.AgentSmokeBoundedAgencyTest' \
    --tests 'atropos.core.agent.BoundedWorkExecutorTest' \
    --tests 'atropos.core.agent.SelfHostAutonomousRunnerTest' \
    --tests 'atropos.core.agent.SelfHostCandidateJarBuilderTest' \
    --tests 'atropos.core.agent.SelfHostContextPreflightTest' \
    --tests 'atropos.core.agent.SelfHostCradleRuntimeStateTest' \
    --tests 'atropos.core.agent.SelfHostCradleVerificationGateTest' \
    --tests 'atropos.core.agent.SelfHostDocumentPlanIntegrationTest' \
    --tests 'atropos.core.agent.SelfHostDocumentPlanTest' \
    --tests 'atropos.core.agent.SelfHostEvidenceBundleExporterTest' \
    --tests 'atropos.core.agent.SelfHostEvidenceProvenanceTest' \
    --tests 'atropos.core.agent.SelfHostEvidenceTextCodecTest' \
    --tests 'atropos.core.agent.SelfHostFailureCodeTest' \
    --tests 'atropos.core.agent.SelfHostGitBaselineReaderTest' \
    --tests 'atropos.core.agent.SelfHostGitStatusEvidenceTest' \
    --tests 'atropos.core.agent.SelfHostGoalQueryServiceTest' \
    --tests 'atropos.core.agent.SelfHostGoalServiceTest' \
    --tests 'atropos.core.agent.SelfHostInstalledProofEvidenceTest' \
    --tests 'atropos.core.agent.SelfHostMutationPayloadParserTest' \
    --tests 'atropos.core.agent.SelfHostMutationVerificationGateTest' \
    --tests 'atropos.core.agent.SelfHostPromotionGateContractTest' \
    --tests 'atropos.core.agent.SelfHostPromotionServiceTest' \
    --tests 'atropos.core.agent.SelfHostRecoveryContinuationTest' \
    --tests 'atropos.core.agent.SelfHostRunProofBuilderTest' \
    --tests 'atropos.core.agent.SelfHostRuntimeJarLocatorTest' \
    --tests 'atropos.core.agent.SelfHostRuntimeRunLimitsTest' \
    --tests 'atropos.core.agent.SelfHostSafetyHardFailGateTest' \
    --tests 'atropos.core.agent.SelfHostStartupContinuationServiceTest' \
    --tests 'atropos.core.agent.SelfHostStateSnapshotRecorderTest' \
    --tests 'atropos.core.agent.SelfHostWorktreeNodeExecutorTest' \
    --tests 'atropos.core.agent.Utf8BoundedBuilderTest' \
    --tests 'atropos.core.agent.AgentAskAnswerNormalizerTest' \
    --tests 'atropos.core.agent.AgentFailureSummaryTest' \
    --tests 'atropos.core.agent.AgentPromptContractTest' \
    --tests 'atropos.core.agent.AgentProviderContextBoundaryTest' \
    --tests 'atropos.core.agent.AgentSecurityRedactionSurfaceTest' \
    --tests 'atropos.core.agent.AgentSelfBuildLoopTest' \
    --tests 'atropos.core.agent.AgentSourceContextRequirementTest' \
    --tests 'atropos.core.agent.BatchGateTest' \
    --tests 'atropos.core.agent.GoalContinuationServiceTest' \
    --tests 'atropos.core.agent.GoalEvidenceGateTest' \
    --tests 'atropos.core.agent.GoalRunStoreTest' \
    --tests 'atropos.core.agent.LeaseTokenDigestTest' \
    --tests 'atropos.core.agent.LeaseTokenPersistenceTest' \
    --tests 'atropos.core.agent.RepositoryImpactPlannerTest' \
    --tests 'atropos.core.agent.ResumableGoalTest' \
    --tests 'atropos.core.agent.SupervisedSessionStoreLeaseTokenTest' \
    --tests 'atropos.core.agent.WorkerCodeProposalServiceTest' \
    --tests 'atropos.core.approval.PendingApprovalStoreTest' \\
    --tests 'atropos.core.artifact.AppFactoryRunProofTest' \\
    --tests 'atropos.core.artifact.ArtifactDeliverableTest' \\
    --tests 'atropos.core.artifact.ArtifactVerificationServiceTest' \\
    --tests 'atropos.core.artifact.SafeJarSwapGateTest' \\
    --tests 'atropos.core.artifact.export.ArtifactLandingTest' \\
    --tests 'atropos.core.artifact.export.HandoffExporterTest' \\
    --tests 'atropos.core.auditor.AuditorServiceTest' \\
    --tests 'atropos.core.auth.AuthCascadeResolverTest' \\
    --tests 'atropos.core.auth.AuthorityAttestationTest' \\
    --tests 'atropos.core.auth.AuthorityMarkdownParserTest' \\
    --tests 'atropos.core.auth.SwarmMdLoaderTest' \\
    --tests 'atropos.core.checkpoint.CheckpointSummaryTest' \\
    --tests 'atropos.core.custodian.CustodianServiceTest' \\
    --tests 'atropos.core.dag.DagExecutionServiceTest' \\
    --tests 'atropos.core.dag.DagNodeCheckEvaluatorTest' \\
    --tests 'atropos.core.dag.DagNodeProposalsTest' \\
    --tests 'atropos.core.dag.DagServiceTest' \\
    --tests 'atropos.core.dag.DocumentIngestionServiceTest' \\
    --tests 'atropos.core.dag.ExecutionDagStoreTest' \\
    --tests 'atropos.core.director.DirectorDagSupervisorTest' \\
    --tests 'atropos.core.director.DirectorServiceTest' \\
    --tests 'atropos.core.dopamine.DopamineRewardSystemTest' \\
    --tests 'atropos.core.evidence.EvidenceCollectorTest' \\
    --tests 'atropos.core.evaluation.AtroposMetricsTest' \\
    --tests 'atropos.core.evaluation.BenchmarkRunnerTest' \\
    --tests 'atropos.core.evaluation.EvaluationEngineTest' \\
    --tests 'atropos.core.evaluation.EvidenceStoreTest' \\
    --tests 'atropos.core.evaluation.ReleaseClassificationTest' \\
    --tests 'atropos.core.evaluation.ReleaseGateEvaluatorTest' \\
    --tests 'atropos.core.execution.LocalWorkQueueTest' \\
    --tests 'atropos.core.hierarchy.HierarchyRegistryTest' \\
    --tests 'atropos.core.hr.HrRouterServiceTest' \\
    --tests 'atropos.core.interrupt.FrozenRunStoreTest' \\
    --tests 'atropos.core.interrupt.InterruptControllerTest' \\
    --tests 'atropos.core.journal.EventJournalServiceTest' \\
    --tests 'atropos.core.memory.LargeMemoryRecallTest' \\
    --tests 'atropos.core.memory.LocalMemoryStoreTest' \\
    --tests 'atropos.core.memory.MemoryBackendProbeTest' \\
    --tests 'atropos.core.memory.MemorySourceChunkerTest' \\
    --tests 'atropos.core.memory.SqliteVecMemoryIndexTest' \\
    --tests 'atropos.core.observability.EventPublisherTest' \\
    --tests 'atropos.core.observability.ExecutionEventTest' \\
    --tests 'atropos.core.observability.ExecutionHistoryStoreTest' \\
    --tests 'atropos.core.observability.Phase20ObservabilityExtensionsTest' \\
    --tests 'atropos.core.observability.ProvenanceStreamTest' \\
    --tests 'atropos.core.observability.RunExportTest' \\
    --tests 'atropos.core.observability.RunObserverTest' \\
    --tests 'atropos.core.observability.UiCapabilitiesTest' \\
    --tests 'atropos.core.phase20.AmendmentGateTest' \\
    --tests 'atropos.core.phase20.AmendmentRegistryTest' \\
    --tests 'atropos.core.phase20.AntiGamingAuditorTest' \\
    --tests 'atropos.core.phase20.EvidenceLedgerTest' \\
    --tests 'atropos.core.phase20.GovernanceCandidatesTest' \\
    --tests 'atropos.core.phase20.GovernanceLedgerTest' \\
    --tests 'atropos.core.phase20.GovernanceMetricsTest' \\
    --tests 'atropos.core.phase20.InvariantContractCatalogTest' \\
    --tests 'atropos.core.phase20.LakehouseLedgersTest' \\
    --tests 'atropos.core.phase20.LakehouseRetrieveTest' \\
    --tests 'atropos.core.phase20.ManifestBuilderTest' \\
    --tests 'atropos.core.phase20.MemoryLedgerTest' \\
    --tests 'atropos.core.phase20.Phase20AuditLogTest' \\
    --tests 'atropos.core.phase20.Phase20ClaimTest' \\
    --tests 'atropos.core.phase20.Phase20LawsTest' \\
    --tests 'atropos.core.phase20.Phase20LoopTest' \\
    --tests 'atropos.core.phase20.PolicyGateTest' \\
    --tests 'atropos.core.phase20.ProposalGateTest' \\
    --tests 'atropos.core.phase20.ProposalGeneratorTest' \\
    --tests 'atropos.core.phase20.ProposalStoreTest' \\
    --tests 'atropos.core.phase20.ReproducibilityGateTest' \\
    --tests 'atropos.core.phase20.SelfBuildValidationRuleTest' \\
    --tests 'atropos.core.phase20.SelfImprovementLawsTest' \\
    --tests 'atropos.core.phase20.SelfImprovementLoopTest' \\
    --tests 'atropos.core.phase20.SelfImprovementRollbackTest' \\
    --tests 'atropos.core.phase20.StructuralManifestTest' \\
    --tests 'atropos.core.phase20.SuperiorityAddendumTest' \\
    --tests 'atropos.core.phase20.SuperiorityPrimitivesTest' \\
    --tests 'atropos.core.planning.GraphClaimServiceTest' \\
    --tests 'atropos.core.planning.GraphTransitionServiceTest' \\
    --tests 'atropos.core.planning.InternalPlanShapeTest' \\
    --tests 'atropos.core.planning.InternalPlanningGraphServiceTest' \\
    --tests 'atropos.core.planning.PlanningGraphPluginRegistryTest' \\
    --tests 'atropos.core.recovery.CrashRecoveryServiceTest' \\
    --tests 'atropos.core.recovery.RestartCoordinatorTest' \\
    --tests 'atropos.core.recovery.RuntimeContinuitySupervisorTest' \\
    --tests 'atropos.core.specgraph.ExportBundleReaderTest' \\
    --tests 'atropos.core.specgraph.ExportBundleVerifierTest' \\
    --tests 'atropos.core.specgraph.HandoffDagTranslatorTest' \\
    --tests 'atropos.core.specgraph.HandoffParserTest' \\
    --tests 'atropos.core.storage.BlobObjectTest' \\
    --tests 'atropos.core.storage.GcMetricsReporterTest' \\
    --tests 'atropos.core.storage.GcPolicyEnforcerTest' \\
    --tests 'atropos.core.storage.GcSweeperTest' \\
    --tests 'atropos.core.storage.GcWatermarkTest' \\
    --tests 'atropos.core.storage.LocalDiskStorageDriverTest' \\
    --tests 'atropos.core.storage.RetentionPolicyTest' \\
    --tests 'atropos.core.storage.StorageCollectionTest' \\
    --tests 'atropos.core.storage.StorageConstitutionTest' \\
    --tests 'atropos.core.storage.StorageGovernanceAtomsTest' \\
    --tests 'atropos.core.storage.StorageIntegrityCheckerTest' \\
    --tests 'atropos.core.storage.StorageQuotaTrackerTest' \\
    --tests 'atropos.core.storage.StorageRetentionRuleTest' \\
    --tests 'atropos.core.storage.StorageSupervisorTest' \\
    --tests 'atropos.core.territory.SubagentSpawnServiceTest' \\
    --tests 'atropos.core.territory.TerritoryEnforcerTest' \\
    --tests 'atropos.core.territory.TerritoryGrantServiceTest' \\
    --tests 'atropos.core.territory.TerritoryMonitorCostIntegrationTest' \\
    --tests 'atropos.core.territory.TerritoryMonitorCostTest' \\
    --tests 'atropos.core.territory.TerritoryServiceTest' \\
    --tests 'atropos.core.verifier.ConstraintSolverEvaluatorExtendedTest' \\
    --tests 'atropos.core.verifier.ConstraintSolverEvaluatorTest' \\
    --tests 'atropos.core.worktree.GitFailureReasonTest' \\
    --tests 'atropos.core.worktree.IsolatedWorktreeServiceTest' \\
    --tests 'atropos.core.worktree.WorktreePatchPathsTest' \\
    --tests 'atropos.core.worktree.WorktreeRecordCodecTest' \\
+    --tests 'atropos.core.AtroposRepoRootLocatorTest' \\
    --tests 'atropos.core.GenerationParametersTest' \\
    --tests 'atropos.core.autonomy.RewardPenaltyStoreTest' \\
    --tests 'atropos.core.contract.SurfaceContractsTest' \\
    --tests 'atropos.core.endpoint.OperationEndpointManifestTest' \\
    --tests 'atropos.core.ingest.AttachmentReaderTest' \\
    --tests 'atropos.core.ingest.DocxTextExtractorTest' \\
    --tests 'atropos.core.ingest.IngestTerritoryTest' \\
    --tests 'atropos.core.ingest.MentionResolverTest' \\
    --tests 'atropos.core.ingest.PdfTextExtractorTest' \\
    --tests 'atropos.core.intent.IntentEnvelopeTest' \\
    --tests 'atropos.core.intent.IntentLayerTest' \\
    --tests 'atropos.core.intent.MentionExtractorTest' \\
    --tests 'atropos.core.intent.MessyIntentParserTest' \\
    --tests 'atropos.core.intent.Sd5B0XPoliciesTest' \\
    --tests 'atropos.core.intent.Sd5HumanIntentInvariantsTest' \\
    --tests 'atropos.core.json.JsonStringFieldTest' \\
    --tests 'atropos.core.knowledge.SelfImprovingCompilationLoopTest' \\
    --tests 'atropos.core.monitor.ActivityStreamTest' \\
    --tests 'atropos.core.multimodal.LivePreviewEvidenceServiceTest' \\
    --tests 'atropos.core.nl.NlEntryPipelineTest' \\
    --tests 'atropos.core.output.OutputModeDetectorTest' \\
    --tests 'atropos.core.parity.SurfaceContractTest' \\
    --tests 'atropos.core.parity.SurfaceParityProbeTest' \\
    --tests 'atropos.core.parser.TreeSitterGrammarBridgeExtendedTest' \\
    --tests 'atropos.core.parser.TreeSitterGrammarBridgeTest' \\
    --tests 'atropos.core.platform.PlatformInterfacesTest' \\
    --tests 'atropos.core.platform.PlatformModuleTopologyTest' \\
    --tests 'atropos.core.platform.PlatformWireTest' \\
    --tests 'atropos.core.platform.SharedCoreTest' \\
    --tests 'atropos.core.preview.LivePreviewServiceTest' \\
    --tests 'atropos.core.preview.PreviewEvidenceTest' \\
    --tests 'atropos.core.project.ProjectRegistryTest' \\
    --tests 'atropos.core.thinking.PipelineNarratorTest' \\
    --tests 'atropos.core.thinking.ThinkingDepthLadderTest' \\
    --tests 'atropos.core.thinking.ThinkingRecordTest' \\
    --tests 'atropos.core.thinking.ThinkingStreamTest' \\
    --tests 'atropos.core.time.SystemClockTest' \\
    --tests 'atropos.core.welcome.WelcomeArtifactTest' \\
    --tests 'atropos.cli.shell.ShellBoundedAgencyTest' \
    --tests 'atropos.cli.GitMutationCommandTest' \
    --tests 'atropos.core.worktree.BoundedGitWorktreeCommandRunnerTest' \
    --tests 'atropos.core.verification.GateReachabilityCheckerTest' \
    --tests 'atropos.core.verification.AcceptanceVelocityTest' \
    --tests 'atropos.core.verification.GitHubActionsCompileRunnerTest' \
    --tests 'atropos.core.security.ContextPathExclusionsTest' \
    --tests 'atropos.core.verification.AdmissionControllerTest' \
    --tests 'atropos.core.verification.ArchitectureComplianceCheckerTest' \
    --tests 'atropos.core.verification.ArchitectureSourceMaskerTest' \
    --tests 'atropos.core.verification.AssertionNamingTest' \
    --tests 'atropos.core.verification.AuthorityAttestationTest' \
    --tests 'atropos.core.verification.BatchReporterTest' \
    --tests 'atropos.core.verification.CompletionCalculusTest' \
    --tests 'atropos.core.verification.DeterministicVerifierTest' \
    --tests 'atropos.core.verification.FalseGreenGuardTest' \
    --tests 'atropos.core.verification.GoalInvariantSetTest' \
    --tests 'atropos.core.verification.GoalRunTest' \
    --tests 'atropos.core.verification.GovernedCompileGateTest' \
    --tests 'atropos.core.verification.IntegrityProofsTest' \
    --tests 'atropos.core.verification.OutputValidatorTest' \
    --tests 'atropos.core.verification.PrecedenceLatticeTest' \
    --tests 'atropos.core.verification.ProposalSixFieldsTest' \
    --tests 'atropos.core.verification.RiskyStdlibScannerTest' \
    --tests 'atropos.core.verification.SourceDoc2RulesTest' \
    --tests 'atropos.core.verification.TerritoryGrantTest' \
    --tests 'atropos.core.verification.VerifiedCompletionGateTest' \
    --tests 'atropos.core.security.DeviceSecretVaultKeyProviderTest' \
    --tests 'atropos.core.security.KeyDoctorServiceTest' \
    --tests 'atropos.core.security.KnownSecretEgressTest' \
    --tests 'atropos.core.security.RedactionFilterTest' \
    --tests 'atropos.core.security.SecretEgressGateTest' \
    --tests 'atropos.core.security.SecretEnrollmentSourceTest' \
    --tests 'atropos.core.security.SecretSinkMatrixTest' \
    --tests 'atropos.core.security.SecretVaultKeyProviderTest' \
    --tests 'atropos.core.security.SecretVaultRuntimeProofTest' \
    --tests 'atropos.core.security.SourceSecretScannerTest' \
    --tests 'atropos.core.security.TokenIsolationVaultEncryptionContractTest' \
    --tests 'atropos.core.security.TokenIsolationVaultTest' \
    --tests 'atropos.core.security.VaultPathResolverTest' \
    --tests 'atropos.core.security.VaultReadResultTest' \
    --tests 'atropos.core.BuildStampTest' \
    --tests 'atropos.core.SelfUpdateTest' \
    --tests 'atropos.core.paid.EmergencyPaidGateTest' \
    --tests 'atropos.core.autonomous.AutonomousBacklogManagerTest' \
    --tests 'atropos.core.autonomous.AutonomousLearningAdvisorTest' \
    --tests 'atropos.core.autonomous.AutonomousOrchestratorLearningTest' \
    --tests 'atropos.core.github.GitHubApiClientTest' \
    --tests 'atropos.core.github.GitHubDeviceAuthClientTest' \
    --tests 'atropos.core.github.GitHubBindingTest' \
    --tests 'atropos.core.scavenge.GitHubScavengerTest'
fi

echo "=== DIFF CHECK ==="
git diff --check

echo "=== NPM INSTALLER CONTRACT ==="
bash scripts/npm-installer-contract-test.sh

echo "=== GITHUB ACTION CONTRACT ==="
bash scripts/atropos-verify-action-contract-test.sh

echo "=== HOSTED TEST SELECTOR CONTRACT ==="
bash scripts/hosted-test-selector-contract.sh

echo "=== MCP EXAMPLE CONTRACT ==="
bash scripts/mcp-example-contract-test.sh

echo "=== GITHUB WRITE CONTRACT ==="
bash scripts/github-write-contract-test.sh

echo "ATROPOS_WORKTREE_VERIFY_OK"
