#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALLER="$ROOT/install.sh"

grep -Fq 'HOST_PREFIX="${PREFIX:-}"' "$INSTALLER"
grep -Fq 'CONFIG_DIR="${ATROPOS_CONFIG_DIR:-${ATROPOS_PREFIX:-$HOME/.atropos}}"' "$INSTALLER"
grep -Fq 'if [ -n "$HOST_PREFIX" ]; then' "$INSTALLER"
grep -Fq 'mkdir -p "$CONFIG_DIR" "$CONFIG_DIR/provider" "$BIN_DIR"' "$INSTALLER"
grep -Fq "printf '%s\\n' '{}' > \"\$CONFIG_DIR/config.json\"" "$INSTALLER"
grep -Fq "printf '%s\\n' '[]' > \"\$CONFIG_DIR/provider/providers.json\"" "$INSTALLER"
grep -Fq '"$BIN_DIR/atropos" --health' "$INSTALLER"
grep -Fq '"$BIN_DIR/atropos" doctor --first-run' "$INSTALLER"
grep -Fq '"$BIN_DIR/atropos" --version' "$INSTALLER"
grep -Fq 'doctor: PASS' "$INSTALLER"
grep -Fq 'uname -s' "$INSTALLER"
grep -Fq 'uname -m' "$INSTALLER"
grep -Fq 'termux-$CPU_ARCH' "$INSTALLER"
grep -Fq 'termux-*) BIN_DIR="$HOST_PREFIX/bin"' "$INSTALLER"
grep -Fq 'ATROPOS_PLATFORM' "$INSTALLER"
grep -Fq 'ATROPOS_CONFIG_DIR' "$INSTALLER"
grep -Fq 'refusing to install an unverified jar' "$INSTALLER"
grep -Fq 'checksum mismatch' "$INSTALLER"
grep -Fq 'releases/download/latest/ATROPOS.jar' "$INSTALLER"
grep -Fq 'releases/download/$VERSION/ATROPOS.jar' "$INSTALLER"
grep -Fq 'DOWNLOAD=' "$INSTALLER"
grep -Fq '$DOWNLOAD "$TMP" "$JAR_URL"' "$INSTALLER"
grep -Fq 'export ATROPOS_PLATFORM=' "$INSTALLER"
grep -Fq 'chmod +x "$BIN_DIR/atropos"' "$INSTALLER"
grep -Fq 'invalid repository; expected owner/name' "$INSTALLER"
grep -Fq 'invalid version; expected latest or a v-prefixed release tag' "$INSTALLER"
grep -Fq '*/*/*' "$INSTALLER"

printf '%s\n' 'ATROPOS_INSTALL_CONTRACT_OK'
