#!/usr/bin/env python3
"""ATROPOS progress-ledger tool: parallel-safe append for multiple agents.

WHY THIS EXISTS
---------------
AGENTS.md section 2 mandates that every agent append one row per coherent batch.
Two agents doing that in the same file, on divergent branches, conflict on every
single batch: git sees two different insertions at the same anchor (end of the
section) and cannot order them. That is not a merge-skill problem, it is a data
model problem — a shared append-only log stored as one hand-edited file has no
conflict-free merge.

THE FIX
-------
1. Each batch writes ONE NEW FILE under ledger/entries/. Filenames carry the UTC
   timestamp, the agent slug, and the batch slug, so two agents never target the
   same path. Git merges disjoint file additions with zero conflicts.
2. No agent ever edits another agent's entry file. Append-only stops being a
   convention enforced by care and becomes a property of the layout.
3. AGENTS.md section 2 is COMPILED from those entries, between sentinel markers,
   in a total order every agent computes identically. It is a derived view, not a
   source of truth, so a conflict inside the generated block is never a data
   loss: re-running `compile` reconstructs it from the entries that already
   merged cleanly.
4. Percentages are derived. Entries declare `phase_deltas` (phase, from, to) in
   front matter; the current-state table and weighted overall are computed from
   the locked baselines plus the ordered deltas. Two agents can never both
   recompute "overall 42 -> 43" from a stale reading and double-count, because
   neither writes the total by hand. Overlapping claims on one phase are flagged
   as DELTA REBASE rather than silently summed.
5. Atom claims (ledger/claims/) make duplicated work loud instead of silent. Two
   agents claiming one atom collide on one path, which surfaces at merge time as
   a conflict on a claim file — the signal you want — instead of two agents
   quietly implementing the same atom twice.

USAGE
    scripts/ledger.py new --agent "Claude (claude-opus-5)" --batch p11-foo \
        --atoms HOE-A01 --predicate "..." --why "..." [--phase-delta 11:65:78]
    scripts/ledger.py compile          # rewrite AGENTS.md section 2 from entries
    scripts/ledger.py check            # verify AGENTS.md matches entries (CI)
    scripts/ledger.py view [--index]   # print the ledger
    scripts/ledger.py claim HOE-A01 --agent "..."   # take an atom
    scripts/ledger.py release HOE-A01 --agent "..." # give it back
    scripts/ledger.py claims           # list live claims
    scripts/ledger.py selftest         # prove parallel merges stay clean
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ENTRY_DIR = REPO_ROOT / "ledger" / "entries"
CLAIM_DIR = REPO_ROOT / "ledger" / "claims"
AGENTS_PATH = REPO_ROOT / "AGENTS.md"

BEGIN = "<!-- LEDGER:BEGIN — generated by scripts/ledger.py compile; do not hand-edit -->"
END = "<!-- LEDGER:END -->"

# Locked baselines from AGENTS.md section 1. Never edited by this tool; deltas
# are applied on top so the originals stay auditable.
PHASE_BASELINES = {
    0: 75, 1: 80, 2: 70, 3: 75, 4: 85, 5: 65,
    6: 80, 7: 50, 8: 80, 9: 60, 10: 55, 11: 65,
    12: 40, 13: 70, 14: 35, 15: 40, 16: 30,
    17: 25, 18: 20, 19: 20, 20: 12,
}
HORIZONS = [
    ("I Foundation 0-10", 25, 72, list(range(0, 11))),
    ("II Self-build + Hierarchy 11-16", 25, 55, list(range(11, 17))),
    ("III Multimodal + Multiplatform 17-18", 10, 22, [17, 18]),
    ("IV App Factory 19", 20, 20, [19]),
    ("V Phase 20 Autonomy", 10, 12, [20]),
]
HOE_WEIGHT, HOE_BASELINE = 10, 32


def slug(text: str) -> str:
    out = re.sub(r"[^a-zA-Z0-9]+", "-", text.strip().lower()).strip("-")
    return out or "unnamed"


def parse_entry(path: Path) -> dict:
    """Read one entry file: '---' front matter then verbatim body."""
    text = path.read_text("utf-8")
    meta: dict = {}
    body = text
    if text.startswith("---\n"):
        raw, _, body = text[4:].partition("\n---\n")
        for line in raw.split("\n"):
            if ":" not in line:
                continue
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    deltas = []
    for item in filter(None, (meta.get("phase_deltas") or "").split(",")):
        bits = item.split(":")
        if len(bits) == 3:
            try:
                deltas.append((int(bits[0]), float(bits[1]), float(bits[2])))
            except ValueError:
                pass
    return {
        "path": path,
        "timestamp": meta.get("timestamp", ""),
        "agent": meta.get("agent", "unknown"),
        "batch": meta.get("batch", path.stem),
        "atoms": meta.get("atoms", ""),
        "phase_deltas": deltas,
        "body": body.strip("\n"),
    }


def sort_key(entry: dict) -> tuple:
    """Total order, identical on every machine.

    Timestamps collide (agents round to the minute) and clocks skew across
    machines, so ties break on agent then batch then filename. Every agent
    therefore compiles byte-identical output from the same entry set, which is
    what makes the generated block mergeable by regeneration.
    """
    return (entry["timestamp"], entry["agent"], entry["batch"], entry["path"].name)


def load_entries() -> list[dict]:
    if not ENTRY_DIR.is_dir():
        return []
    return sorted((parse_entry(p) for p in ENTRY_DIR.glob("*.md")), key=sort_key)


def derive_state(entries: list[dict]) -> tuple[dict, list[str]]:
    """Apply ordered deltas to the locked baselines. Never sums blindly."""
    current = dict(PHASE_BASELINES)
    warnings: list[str] = []
    for entry in entries:
        for phase, frm, to in entry["phase_deltas"]:
            if phase not in current:
                warnings.append(f"{entry['batch']}: unknown phase {phase}")
                continue
            if abs(current[phase] - frm) > 0.01:
                warnings.append(
                    f"DELTA REBASE NEEDED — {entry['batch']} declares phase {phase} "
                    f"{frm:g}%->{to:g}% but the running value is {current[phase]:g}%; "
                    "another agent moved this phase first. Re-derive from the current value."
                )
            current[phase] = to
    return current, warnings


def weighted_overall(current: dict) -> tuple[float, list[str]]:
    lines, total = [], 0.0
    for name, weight, baseline, phases in HORIZONS:
        moved = [p for p in phases if abs(current[p] - PHASE_BASELINES[p]) > 0.01]
        # Section 1 does not state each horizon's internal weighting, so a phase
        # move is spread evenly across its horizon. Stated, not hidden.
        shift = sum(current[p] - PHASE_BASELINES[p] for p in phases) / len(phases)
        pct = baseline + shift
        contribution = weight * pct / 100.0
        total += contribution
        note = f" (moved: {', '.join(f'P{p}' for p in moved)})" if moved else ""
        lines.append(f"| {name} | {weight}% | {pct:.1f}% | {contribution:.1f}{note} |")
    total += HOE_WEIGHT * HOE_BASELINE / 100.0
    lines.append(f"| HOE Presentation | {HOE_WEIGHT}% | {HOE_BASELINE}% | "
                 f"{HOE_WEIGHT * HOE_BASELINE / 100.0:.1f} |")
    return total, lines


def render_block(entries: list[dict]) -> str:
    current, warnings = derive_state(entries)
    total, horizon_lines = weighted_overall(current)
    out = [BEGIN, ""]
    out.append(f"Entries: {len(entries)} · compiled from `ledger/entries/*.md` · "
               f"derived overall: **≈ {total:.1f}%** (baseline ≈ 42%)")
    out.append("")
    if warnings:
        out.append("**Compiler warnings — resolve before claiming a percentage:**")
        out.extend(f"- {w}" for w in warnings)
        out.append("")
    out.append("### Derived current phase state (baselines in §1 are never edited)")
    out.append("")
    out.append("| Phase | Baseline % | Current % | Moved by |")
    out.append("| --- | --- | --- | --- |")
    movers: dict[int, list[str]] = {}
    for entry in entries:
        for phase, _frm, _to in entry["phase_deltas"]:
            movers.setdefault(phase, []).append(entry["batch"])
    for phase in sorted(PHASE_BASELINES):
        base, now = PHASE_BASELINES[phase], current[phase]
        if abs(base - now) < 0.01:
            continue
        out.append(f"| {phase} | {base:g}% | {now:g}% | {', '.join(movers.get(phase, []))} |")
    out.append("")
    out.append("| Horizon | Weight | Current % | Weighted |")
    out.append("| --- | --- | --- | --- |")
    out.extend(horizon_lines)
    out.append(f"| **DERIVED OVERALL** | | | **≈ {total:.1f}%** |")
    out.append("")
    out.append("### Entries (oldest first; every row preserved verbatim from its entry file)")
    out.append("")
    for entry in entries:
        out.append(f"#### {entry['timestamp']} · Agent: {entry['agent']} · Batch: {entry['batch']}")
        out.append(f"<sub>entry: `{entry['path'].relative_to(REPO_ROOT)}`</sub>")
        out.append("")
        out.append(entry["body"])
        out.append("")
    out.append(END)
    return "\n".join(out)


ROW_HEADER = re.compile(
    r"(?m)^#{3,4} (?P<ts>\S+)\s+·\s+Agent:\s+(?P<agent>.+?)\s+·\s+Batch:\s+(?P<batch>\S+)\s*$"
)


def existing_keys() -> set[tuple[str, str]]:
    return {(e["agent"], e["batch"]) for e in load_entries()}


def harvest_rows(text: str) -> tuple[str, list[Path]]:
    """Absorb hand-appended ledger rows into entry files.

    A peer agent that has not adopted this protocol keeps hand-appending
    '### <ts> · Agent: X · Batch: Y' rows straight into AGENTS.md. Compiling
    from entry files alone would silently drop that work, which is exactly the
    failure this tool exists to prevent. So any row found OUTSIDE the generated
    block is converted into an entry file first, then removed from the prose.
    Nothing is ever deleted without first being preserved as an entry.

    Dedupe is on (agent, batch): harvesting the same row twice is a no-op, so
    this is safe to run on every compile and after every merge.
    """
    ENTRY_DIR.mkdir(parents=True, exist_ok=True)
    known = existing_keys()
    created: list[Path] = []
    matches = list(ROW_HEADER.finditer(text))
    if not matches:
        return text, created
    # Cut each row from its header to the next header or the end of the region.
    spans: list[tuple[int, int, dict]] = []
    for idx, match in enumerate(matches):
        start = match.start()
        end = matches[idx + 1].start() if idx + 1 < len(matches) else len(text)
        body = text[match.end():end]
        # A row ends at a horizontal rule or a new top-level section.
        for terminator in ("\n---\n", "\n## "):
            cut = body.find(terminator)
            if cut != -1:
                end = match.end() + cut
                body = body[:cut]
        spans.append((start, end, {
            "ts": match.group("ts"), "agent": match.group("agent").strip(),
            "batch": match.group("batch").strip(), "body": body,
        }))
    for _start, _end, row in spans:
        key = (row["agent"], row["batch"])
        if key in known:
            continue
        known.add(key)
        try:
            parsed = dt.datetime.fromisoformat(row["ts"].replace("Z", "+00:00"))
            if parsed.tzinfo is None:
                parsed = parsed.replace(tzinfo=dt.timezone.utc)
            parsed = parsed.astimezone(dt.timezone.utc)
            stamp, iso = parsed.strftime("%Y%m%dT%H%M%SZ"), parsed.isoformat().replace("+00:00", "Z")
        except ValueError:
            stamp, iso = re.sub(r"[^0-9TZ]", "", row["ts"])[:16] or "00000000T000000Z", row["ts"]
        body = re.sub(r"(?m)^<sub>entry:.*\n", "", row["body"]).strip("\n")
        atoms = ""
        found = re.search(r"(?m)^- Atoms / phases affected:\s*(.+)$", body)
        if found:
            atoms = found.group(1).strip().replace("`", "")[:120]
        path = ENTRY_DIR / f"{stamp}-{slug(row['agent'])}-{slug(row['batch'])}.md"
        if path.exists():
            continue
        path.write_text(
            "\n".join(["---", f"timestamp: {iso}", f"agent: {row['agent']}",
                       f"batch: {row['batch']}", f"atoms: {atoms}",
                       "phase_deltas: ", "---"]) + "\n" + body + "\n", "utf-8")
        created.append(path)
    # Remove harvested rows from the prose, last first so offsets stay valid.
    for start, end, _row in reversed(spans):
        text = text[:start] + text[end:]
    return text, created


def compile_agents(write: bool = True) -> tuple[bool, str, list[Path]]:
    text = AGENTS_PATH.read_text("utf-8")
    if BEGIN not in text or END not in text:
        # Deliberately inert. AGENTS.md is hash-pinned by its owner (see the
        # gitignored ATROPOS_ROOT_EXPORT_MANIFEST.sha256) and may be under active
        # edit by another agent, so this tool never inserts itself into that file.
        # Adoption is one explicit act by the file's owner: paste the two sentinel
        # lines where the ledger rows belong, then run `compile`. Until then
        # `new`, `view`, `claim`, and `selftest` all work and AGENTS.md is untouched.
        raise SystemExit(
            "AGENTS.md has no ledger sentinels, so it was NOT modified.\n"
            "To adopt the compiled ledger, its owner adds these two lines in §2:\n"
            f"  {BEGIN}\n  {END}\n"
            "Existing hand-written rows above/below are harvested into "
            "ledger/entries/ on the next compile, never deleted."
        )
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    # Harvest only outside the generated block: rows inside it are already ours.
    head, created_head = harvest_rows(head)
    tail, created_tail = harvest_rows(tail)
    harvested = created_head + created_tail
    block = render_block(load_entries())
    updated = head + block + tail
    changed = updated != text
    if write and changed:
        AGENTS_PATH.write_text(updated, "utf-8")
    return changed, block, harvested


def cmd_resolve(_args: argparse.Namespace) -> int:
    """Resolve an AGENTS.md merge conflict without losing either side's rows.

    Conflict markers are stripped so BOTH sides' prose is unioned, every row on
    either side is harvested into an entry file, and the block is recompiled from
    the union. Because entry files are per-batch and merge cleanly on their own,
    the generated block is always reconstructable — a conflict here can cost
    formatting, never a ledger row.
    """
    text = AGENTS_PATH.read_text("utf-8")
    if "<<<<<<<" not in text:
        print("AGENTS.md has no conflict markers; running a normal compile")
        return cmd_compile(_args)
    cleaned = "\n".join(
        line for line in text.split("\n")
        if not line.startswith(("<<<<<<<", "=======", ">>>>>>>"))
    )
    AGENTS_PATH.write_text(cleaned, "utf-8")
    _changed, _block, harvested = compile_agents()
    print(f"resolved AGENTS.md: unioned both sides, harvested {len(harvested)} row(s) "
          f"into ledger/entries/, recompiled the block")
    for path in harvested:
        print(f"  harvested {path.relative_to(REPO_ROOT)}")
    print("now run: git add AGENTS.md ledger/entries && git commit")
    return 0


def cmd_new(args: argparse.Namespace) -> int:
    ENTRY_DIR.mkdir(parents=True, exist_ok=True)
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0)
    stamp = now.strftime("%Y%m%dT%H%M%SZ")
    name = f"{stamp}-{slug(args.agent)}-{slug(args.batch)}.md"
    path = ENTRY_DIR / name
    if path.exists():
        raise SystemExit(f"entry already exists: {path}")
    deltas = ",".join(args.phase_delta or [])
    body = args.body or "\n".join(
        [
            f"- Paths touched: {args.paths or '<exact paths + line deltas>'}",
            f"- Atoms / phases affected: {args.atoms or '<IDs from gap maps>'}",
            f"- Predicate moved: {args.predicate or '<what became true that was false>'}",
            f"- % delta: {args.pct or 'unchanged'}",
            f"- Why the delta is justified: {args.why or '<evidence>'}",
            f"- New overall estimate: derived by scripts/ledger.py from phase_deltas",
            f"- Fingerprints: {args.fingerprints or '<hashes>'}",
        ]
    )
    front = [
        "---",
        f"timestamp: {now.isoformat().replace('+00:00', 'Z')}",
        f"agent: {args.agent}",
        f"batch: {args.batch}",
        f"atoms: {args.atoms or ''}",
        f"phase_deltas: {deltas}",
        "---",
    ]
    path.write_text("\n".join(front) + "\n" + body.strip("\n") + "\n", "utf-8")
    compile_agents()
    print(path.relative_to(REPO_ROOT))
    return 0


def cmd_compile(_args: argparse.Namespace) -> int:
    changed, _block, harvested = compile_agents()
    for path in harvested:
        print(f"harvested hand-appended row -> {path.relative_to(REPO_ROOT)}")
    print("AGENTS.md ledger block " + ("rewritten" if changed else "already current"))
    return 0


def cmd_check(_args: argparse.Namespace) -> int:
    changed, _block, _harvested = compile_agents(write=False)
    if changed:
        print("STALE: AGENTS.md ledger block does not match ledger/entries/. "
              "Run scripts/ledger.py compile", file=sys.stderr)
        return 1
    print("AGENTS.md ledger block matches ledger/entries/")
    return 0


def cmd_view(args: argparse.Namespace) -> int:
    entries = load_entries()
    if args.index:
        for entry in entries:
            print(f"{entry['timestamp']}  {entry['agent']:<28} {entry['batch']:<44} "
                  f"{entry['atoms']}")
    else:
        print(render_block(entries))
    return 0


def claim_path(atom: str) -> Path:
    return CLAIM_DIR / f"{slug(atom)}.claim"


def cmd_claim(args: argparse.Namespace) -> int:
    CLAIM_DIR.mkdir(parents=True, exist_ok=True)
    path = claim_path(args.atom)
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0)
    if path.exists():
        existing = json.loads(path.read_text("utf-8"))
        if existing.get("agent") != args.agent:
            print(f"REFUSED: {args.atom} is claimed by {existing.get('agent')} "
                  f"since {existing.get('claimed_at')} on branch "
                  f"{existing.get('branch')}. Pick another atom or ask for a release.",
                  file=sys.stderr)
            return 2
    path.write_text(json.dumps({
        "atom": args.atom,
        "agent": args.agent,
        "branch": git("rev-parse", "--abbrev-ref", "HEAD") or "unknown",
        "claimed_at": now.isoformat().replace("+00:00", "Z"),
    }, indent=2) + "\n", "utf-8")
    print(f"claimed {args.atom} for {args.agent}: {path.relative_to(REPO_ROOT)}")
    return 0


def cmd_release(args: argparse.Namespace) -> int:
    path = claim_path(args.atom)
    if not path.exists():
        print(f"no claim on {args.atom}")
        return 0
    existing = json.loads(path.read_text("utf-8"))
    if existing.get("agent") != args.agent and not args.force:
        print(f"REFUSED: {args.atom} is claimed by {existing.get('agent')}; "
              "use --force only with the owner's agreement", file=sys.stderr)
        return 2
    path.unlink()
    print(f"released {args.atom}")
    return 0


def cmd_claims(_args: argparse.Namespace) -> int:
    if not CLAIM_DIR.is_dir():
        print("no claims")
        return 0
    for path in sorted(CLAIM_DIR.glob("*.claim")):
        data = json.loads(path.read_text("utf-8"))
        print(f"{data.get('atom'):<16} {data.get('agent'):<30} "
              f"{data.get('claimed_at')}  branch={data.get('branch')}")
    return 0


def git(*args: str, cwd: Path | None = None) -> str:
    proc = subprocess.run(["git", *args], cwd=cwd or REPO_ROOT,
                          capture_output=True, text=True)
    return proc.stdout.strip()


def cmd_selftest(_args: argparse.Namespace) -> int:
    """Prove the claim: two agents, two branches, one batch each, zero conflicts.

    This is the acceptance predicate for the whole design. It builds a throwaway
    repo, has two 'CLIs' each append an entry on its own branch, merges them, and
    asserts the merge is clean and both rows survive in the compiled output.
    """
    tool = Path(__file__).resolve()
    with tempfile.TemporaryDirectory(prefix="atropos-ledger-selftest-") as tmp:
        root = Path(tmp) / "repo"
        (root / "scripts").mkdir(parents=True)
        (root / "ledger" / "entries").mkdir(parents=True)
        (root / "scripts" / "ledger.py").write_text(tool.read_text("utf-8"), "utf-8")
        (root / "AGENTS.md").write_text(
            f"# AGENTS.md\n\n## 2. PROGRESS LEDGER\n\n{BEGIN}\n{END}\n", "utf-8")
        env = {**os.environ, "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t",
               "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@t"}

        def run(*args, cwd=root):
            return subprocess.run(args, cwd=cwd, env=env, capture_output=True, text=True)

        run("git", "init", "-q")
        run("git", "add", "-A")
        run("git", "commit", "-qm", "base")

        def agent_batch(branch: str, agent: str, batch: str, delta: str) -> None:
            run("git", "checkout", "-q", "-b", branch, "main" if branch != "main" else "HEAD")
            subprocess.run([sys.executable, str(root / "scripts" / "ledger.py"), "new",
                            "--agent", agent, "--batch", batch,
                            "--phase-delta", delta, "--predicate", f"{agent} moved something"],
                           cwd=root, env=env, capture_output=True, text=True)
            run("git", "add", "-A")
            run("git", "commit", "-qm", f"{agent}: {batch}")

        run("git", "branch", "-M", "main")
        agent_batch("cli-a", "Claude (claude-opus-5)", "atom-a-001", "11:65:78")
        run("git", "checkout", "-q", "main")
        agent_batch("cli-b", "Codex GPT-5", "atom-b-001", "13:70:74")

        run("git", "checkout", "-q", "cli-a")
        merge = run("git", "merge", "--no-edit", "cli-b")
        conflicts = run("git", "diff", "--name-only", "--diff-filter=U").stdout.strip()

        failures = []
        if conflicts:
            # AGENTS.md may conflict in the generated block; that is recoverable
            # by regeneration and must NOT touch the entry files.
            bad = [c for c in conflicts.split("\n") if not c.endswith("AGENTS.md")]
            if bad:
                failures.append(f"entry files conflicted: {bad}")
            subprocess.run([sys.executable, str(root / "scripts" / "ledger.py"), "compile"],
                           cwd=root, env=env, capture_output=True, text=True)
            run("git", "add", "AGENTS.md")
            run("git", "commit", "-qm", "merge: recompile ledger")

        entries = sorted((root / "ledger" / "entries").glob("*.md"))
        if len(entries) != 2:
            failures.append(f"expected 2 entry files after merge, found {len(entries)}")
        final = (root / "AGENTS.md").read_text("utf-8")
        for needle in ("atom-a-001", "atom-b-001", "Claude (claude-opus-5)", "Codex GPT-5"):
            if needle not in final:
                failures.append(f"compiled ledger lost {needle!r}")
        # Both phase moves must land, and the overall must be derived once.
        if "| 11 |" not in final or "| 13 |" not in final:
            failures.append("derived phase table lost a parallel phase move")
        if "DELTA REBASE" in final:
            failures.append("independent phase moves were wrongly flagged as a rebase")

        # Determinism: compiling twice changes nothing.
        before = (root / "AGENTS.md").read_text("utf-8")
        subprocess.run([sys.executable, str(root / "scripts" / "ledger.py"), "compile"],
                       cwd=root, env=env, capture_output=True, text=True)
        if (root / "AGENTS.md").read_text("utf-8") != before:
            failures.append("compile is not idempotent")

        print(f"merge output: {merge.stdout.strip() or merge.stderr.strip()}")
        print(f"conflicted paths: {conflicts or 'none'}")
        print(f"entry files after merge: {len(entries)}")

        # Scenario 2: the peer never adopted the protocol. It hand-appends a row
        # straight into AGENTS.md, exactly as it does today. A compiler that only
        # read entry files would delete that row on the next compile. It must be
        # harvested instead — this is the case that decides whether the design is
        # safe to land while another CLI is mid-flight.
        agents_md = root / "AGENTS.md"
        peer_row = (
            "\n### 2026-07-30T01:02:03-06:00 · Agent: Peer CLI (unadopted) · Batch: peer-hand-append-001\n"
            "- Paths touched: `src/main/kotlin/atropos/Peer.kt` (+10)\n"
            "- Predicate moved: peer appended without knowing about ledger.py\n"
        )
        text = agents_md.read_text("utf-8")
        agents_md.write_text(text.replace(END, END + peer_row), "utf-8")
        subprocess.run([sys.executable, str(root / "scripts" / "ledger.py"), "compile"],
                       cwd=root, env=env, capture_output=True, text=True)
        after = agents_md.read_text("utf-8")
        harvested = list((root / "ledger" / "entries").glob("*peer-hand-append-001*"))
        if not harvested:
            failures.append("a hand-appended peer row was not harvested into an entry file")
        if "peer-hand-append-001" not in after:
            failures.append("a hand-appended peer row vanished from the compiled ledger")
        if "src/main/kotlin/atropos/Peer.kt" not in after:
            failures.append("harvesting lost the peer row's body")
        # And harvesting twice must not duplicate it.
        subprocess.run([sys.executable, str(root / "scripts" / "ledger.py"), "compile"],
                       cwd=root, env=env, capture_output=True, text=True)
        if agents_md.read_text("utf-8").count("peer-hand-append-001") != after.count("peer-hand-append-001"):
            failures.append("re-compiling duplicated a harvested row")
        print(f"peer row harvested to: {[p.name for p in harvested]}")

        if failures:
            for f in failures:
                print(f"FAIL: {f}", file=sys.stderr)
            return 1
        print("LEDGER_PARALLEL_SELFTEST_OK — two agents merged clean; "
              "unadopted peer's hand-appended row harvested, not lost")
        return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    new = sub.add_parser("new", help="create one entry file for the current batch")
    new.add_argument("--agent", required=True)
    new.add_argument("--batch", required=True)
    new.add_argument("--atoms", default="")
    new.add_argument("--paths", default="")
    new.add_argument("--predicate", default="")
    new.add_argument("--pct", default="")
    new.add_argument("--why", default="")
    new.add_argument("--fingerprints", default="")
    new.add_argument("--body", default="", help="full row body; overrides the field flags")
    new.add_argument("--phase-delta", action="append",
                     help="phase:from:to, e.g. 11:65:78 (repeatable)")
    new.set_defaults(func=cmd_new)

    sub.add_parser("compile", help="rewrite the AGENTS.md ledger block").set_defaults(func=cmd_compile)
    sub.add_parser("resolve", help="resolve an AGENTS.md conflict, keeping every row").set_defaults(func=cmd_resolve)
    sub.add_parser("check", help="fail if AGENTS.md is stale").set_defaults(func=cmd_check)

    view = sub.add_parser("view", help="print the ledger")
    view.add_argument("--index", action="store_true", help="one line per entry")
    view.set_defaults(func=cmd_view)

    claim = sub.add_parser("claim", help="claim an atom before working it")
    claim.add_argument("atom")
    claim.add_argument("--agent", required=True)
    claim.set_defaults(func=cmd_claim)

    release = sub.add_parser("release", help="release an atom claim")
    release.add_argument("atom")
    release.add_argument("--agent", required=True)
    release.add_argument("--force", action="store_true")
    release.set_defaults(func=cmd_release)

    sub.add_parser("claims", help="list live claims").set_defaults(func=cmd_claims)
    sub.add_parser("selftest", help="prove parallel merges stay clean").set_defaults(func=cmd_selftest)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
