package atropos.core.factory

data class FactoryPlan(
    val id: String,
    val prompt: String,
    val intent: String,
    val projectSpec: AppProjectSpec,
    val steps: List<FactoryStep>,
    val paidAllowed: Boolean,
    val queuedWork: List<String>,
    val assetFiles: List<String>,
    val memoryRecordId: String?,
    val projectRecordId: String? = null,
    val generatedProject: GeneratedAppProject? = null,
    val planningDagId: String? = null,
    val plannedAtomIds: List<String> = emptyList(),
    val softFailures: List<String> = emptyList(),
    val promptFingerprint: String? = null,
    val promptSha256: String? = null,
    val promptSpans: String? = null,
    val confidenceScore: Int? = null,
    val confidenceBreakdown: String? = null,
    val researchSha256: String? = null,
    val researchChannels: String? = null,
    val researchState: String? = null,
    val proposalSha256: String? = null,
    val memoryPointers: List<String> = emptyList(),
    val contextHash: String? = null,
    val specGraphStatus: String? = null,
    val eventJournalPath: String? = null
)
