package atropos.core.factory

import atropos.core.security.RedactionFilter
import java.util.Locale

class RepoScaffold(
    private val redactionFilter: RedactionFilter = RedactionFilter(),
    private val sourceTemplate: AppSourceTemplate = AppSourceTemplate(),
    private val authPlanner: AppAuthPlanner = AppAuthPlanner(),
    private val backendPlanner: AppBackendIntegrationPlanner = AppBackendIntegrationPlanner(),
    private val databasePlanner: AppDatabaseSecurityPlanner = AppDatabaseSecurityPlanner()
) {
    fun files(spec: AppProjectSpec, lineage: FactoryLineage? = null): LinkedHashMap<String, String> {
        val packageName = AppProjectGenerator.safeName(spec.intent.name)
        val title = spec.intent.name.replaceFirstChar { it.titlecase(Locale.US) }
        val featureText = redactionFilter.redact(spec.intent.features.joinToString(", ")).ifBlank { "general application" }
        val safePrompt = redactionFilter.redact(spec.prompt)
        val lineageText = lineage?.let {
            "Lineage:\n- prompt_sha256: ${it.promptSha256}\n- prompt_fingerprint: ${it.promptFingerprint}\n- prompt_spans: ${it.promptSpans}\n- research_sha256: ${it.researchSha256}\n"
        }.orEmpty()
        val sourceLineage = lineage?.let {
            "// ATROPOS lineage: project_id=${it.projectId}\n" +
                "// prompt_sha256=${it.promptSha256}\n" +
                "// prompt_fingerprint=${it.promptFingerprint}\n" +
                "// prompt_spans=${it.promptSpans}\n" +
                "// research_sha256=${it.researchSha256}\n"
        }.orEmpty()
        val authPlan = authPlanner.planAuthenticationFlow(spec.intent.kind)
        val plannedFeatures = atropos.core.integration.DependencyDeduplicator.deduplicate(
            spec.intent.features.ifEmpty { listOf(spec.intent.name) }
        )
        val endpointPlan = backendPlanner.planApiEndpoints(plannedFeatures)
        val schemaPlan = databasePlanner.planSchema(spec.intent.name)
        val map = linkedMapOf(
            "src/main/kotlin/$packageName/Main.kt" to sourceLineage + sourceTemplate.mainSource(spec, packageName),
            "src/test/kotlin/$packageName/MainTest.kt" to sourceLineage + sourceTemplate.testSource(spec, packageName),
            "README.md" to "# $title\n\nGenerated by ATROPOS from: $safePrompt\n\nKind: ${spec.intent.kind}\nFeatures: $featureText\n\n## Planned boundaries\n- $authPlan\n- ${endpointPlan.joinToString("; ")}\n- $schemaPlan\n\n$lineageText",
            "LICENSE" to "MIT License\n\nCopyright (c) ATROPOS\n",
            ".gitignore" to "build/\n.gradle/\n.idea/\n",
            "AGENTS.md" to "# $title Repository\n\n- Owner: the repository operator.\n- Territory: generated source and evidence remain inside this repository.\n- Verification: run `./verify.sh` before promoting changes.\n- Evidence: `.atropos/evidence/app-manifest.txt` records the source-tree digest and commit.\n- Secrets: never commit credentials; redact operator prompts before persistence.\n\n$lineageText",
            "verify.sh" to "#!/usr/bin/env sh\nset -eu\nmain=src/main/kotlin/$packageName/Main.kt\ntest=src/test/kotlin/$packageName/MainTest.kt\ncommand -v kotlinc >/dev/null 2>&1 || { printf '%s\\n' 'kotlinc is required for generated-test verification' >&2; exit 1; }\nmkdir -p build\nkotlinc \"\$main\" \"\$test\" -include-runtime -d build/app-tests.jar\njava -cp build/app-tests.jar ${packageName}.MainTestKt\nprintf '%s\\n' APP_FACTORY_VERIFY_OK\n"
        )

        if (spec.intent.kind.lowercase() == "web") {
            map["src/main/resources/static/index.html"] = """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <title>$title</title>
                    <link rel="stylesheet" href="style.css">
                </head>
                <body>
                    <nav class="navbar">
                        <div class="logo">$title</div>
                        <ul class="nav-links">
                            <li><a href="#home">Home</a></li>
                            <li><a href="#features">Features</a></li>
                            <li><a href="#about">About</a></li>
                        </ul>
                    </nav>
                    <main class="content">
                        <h1>Welcome to $title</h1>
                        <form id="action-form">
                            <label for="input-field">Submit feedback:</label>
                            <input type="text" id="input-field" name="feedback" required>
                            <button type="submit">Submit</button>
                        </form>
                    </main>
                    <script src="app.js"></script>
                </body>
                </html>
            """.trimIndent()

            map["src/main/resources/static/style.css"] = """
                /* Design System Colors */
                :root {
                    --primary-color: #0066cc;
                    --background-color: #f5f5f7;
                    --text-color: #1d1d1f;
                }
                body {
                    font-family: sans-serif;
                    background-color: var(--background-color);
                    color: var(--text-color);
                }
                .navbar {
                    display: flex;
                    justify-content: space-between;
                }
                .logo {
                    color: var(--primary-color);
                }
            """.trimIndent()

            map["src/main/resources/static/app.js"] = """
                console.log('App initialized');
                document.getElementById('action-form')?.addEventListener('submit', (e) => {
                    e.preventDefault();
                    alert('Submitted successfully');
                });
            """.trimIndent()
        }

        return map
    }
}
