package atropos.core.factory

import atropos.core.security.RedactionFilter
import java.util.Locale

class RepoScaffold(
    private val redactionFilter: RedactionFilter = RedactionFilter(),
    private val sourceTemplate: AppSourceTemplate = AppSourceTemplate()
) {
    fun files(spec: AppProjectSpec): LinkedHashMap<String, String> {
        val packageName = safeId(spec.intent.name)
        val title = spec.intent.name.replaceFirstChar { it.titlecase(Locale.US) }
        val featureText = redactionFilter.redact(spec.intent.features.joinToString(", ")).ifBlank { "general application" }
        val safePrompt = redactionFilter.redact(spec.prompt)
        return linkedMapOf(
            "src/main/kotlin/$packageName/Main.kt" to sourceTemplate.mainSource(spec, packageName),
            "src/test/kotlin/$packageName/MainTest.kt" to sourceTemplate.testSource(spec, packageName),
            "README.md" to "# $title\n\nGenerated by ATROPOS from: $safePrompt\n\nKind: ${spec.intent.kind}\nFeatures: $featureText\n",
            "LICENSE" to "MIT License\n\nCopyright (c) ATROPOS\n",
            ".gitignore" to "build/\n.gradle/\n.idea/\n",
            "AGENTS.md" to "# $title Repository\n\n- Owner: the repository operator.\n- Territory: generated source and evidence remain inside this repository.\n- Verification: run `./verify.sh` before promoting changes.\n- Evidence: `.atropos/evidence/app-manifest.txt` records the source-tree digest and commit.\n- Secrets: never commit credentials; redact operator prompts before persistence.\n",
            "verify.sh" to "#!/usr/bin/env sh\nset -eu\nmain=src/main/kotlin/$packageName/Main.kt\ntest=src/test/kotlin/$packageName/MainTest.kt\ncommand -v kotlinc >/dev/null 2>&1 || { printf '%s\\n' 'kotlinc is required for generated-test verification' >&2; exit 1; }\nmkdir -p build\nkotlinc \"\$main\" \"\$test\" -include-runtime -d build/app-tests.jar\njava -cp build/app-tests.jar ${packageName}.MainTestKt\nprintf '%s\\n' APP_FACTORY_VERIFY_OK\n"
        )
    }

    private fun safeId(value: String): String {
        val normalized = value.replace(Regex("[^A-Za-z0-9_]"), "_").lowercase(Locale.US)
        return if (normalized.firstOrNull()?.isLetter() == true || normalized.firstOrNull() == '_') normalized else "app_$normalized"
    }

}
